<?php
// $Id: tow.module,v 1.0.0.0 2011/02/28 23:42:15 tow Exp $
/**
 * @file
 * Custom code for tow.
 */

include_once('./' . drupal_get_path('module', 'tow') . '/tow_table_filter.inc');
include_once('./' . drupal_get_path('module', 'tow') . '/tow_table_sql.inc');
include_once('./' . drupal_get_path('module', 'tow') . '/tow_table.inc');
include_once('./' . drupal_get_path('module', 'tow') . '/tow_record.inc');
include_once('./' . drupal_get_path('module', 'tow') . '/tow_dataset.inc');
include_once('./' . drupal_get_path('module', 'tow') . '/tow_table_theme.inc');
include_once('./' . drupal_get_path('module', 'tow') . '/tow_validate.inc');

include_once('./' . drupal_get_path('module', 'tow') . '/tow_pma_menu.inc');
include_once('./' . drupal_get_path('module', 'tow') . '/tests/tow_tests.inc');

// Validation constants, min and max number of columns in a table 
define("MIN_FIELDS_IN_TABLE", 1);
define("MAX_FIELDS_IN_TABLE", 20);

/**
 * Declare array of fields that may be used.
 */
function tow_possible_fields() {
  return array('int', 'char', 'float', 'bool', 'text', 'enum', 'date', 'datetime', 'time', 'timestamp', 'code');
}

/**
 * Implementation of hook_views_api().
 */
function tow_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'tow'),
  );
}

/**
 * Implementation of hook_theme()
 */
function tow_theme() {
  return array(
    'tabular_form' => array(
      'arguments' => array(
        'form' => NULL,
      ),
    ),
    'sortable_table' =>array(
      'arguments' => array(
        'header' => array(),
        'rows' => array(),
        'nid' => NULL,
        'uid' => NULL,
        'attributes' => array(),
        'caption' => NULL
      ),
    ),
    'tow_theme_dataset_badge' => array(
      'arguments' => array(
        'posted_by' => NULL,
        'count' => NULL,
        'searches' => NULL,
        'added' => NULL,
        'updated' => NULL,
        'access' => NULL,
      ),
      'template' => 'templates/tow_block-dataset_badge',
    ),
    'tow_theme_dataset_attachment' => array(
      'arguments' => array(
        'description' => NULL,
        'edit_description' => NULL,
        'categories' => NULL,
        'edit_categories' => NULL,
      ),
      'template' => 'templates/tow_theme_dataset_attachment',
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function tow_menu() {
  $items = array();
  
  $items['data'] = array(
    'access arguments' => array('access content'),
    'title' => 'Data',
    'page callback' => 'tow_data',
    'menu_name' => 'primary-links',
  );
  
  $items['table'] = array(
    'access arguments' => array('access content'),
    'page arguments' => array(1),
    'page callback' => 'tow_table_callback',
    'file' => 'tow_table.inc',
  );
  
  $items['table/%/truncate'] = array(
    'title' => 'Truncate',  
    'access arguments' => array('delete own record content'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tow_table_truncate_confirm', 1),
    'file' => 'tow_table_truncate.inc',
    'type' => MENU_CALLBACK
  );
  
  $items['dataset/%/maintenance'] = array(
    'title' => 'Maintenance mode',
    'access arguments' => array('edit own dataset content'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tow_dataset_maintenance_confirm', 1),
    'file' => 'tow_dataset.inc',
    'type' => MENU_CALLBACK
  );
  
  $items = array_merge($items, tow_tests_menu());
  return $items;
}

function tow_data() {
  return l('Create a new dataset', 'node/add/dataset', array('attributes' => array('class' => 'create-dataset-link')));
}

/**
 * Implementation of hook_nodeapi().
 */
function tow_nodeapi(&$node, $op) {
  // Delete all records that have ref to the table being deleted
  // Delete all tables that have ref to the dataset being deleted
  if ($op == 'delete') {    
    $children_type = _tow_children_type($node->type);
    if ($children_type) {
      $res = db_query("SELECT nid FROM {content_type_%s} WHERE field_{%s}_nid = %d", $children_type, $node->type, $node->nid);
      while($node_to_delete = db_fetch_object($res))
        node_delete($node_to_delete->nid);
    }
  }
    
  if ($op == 'view') {
    if ($node->type == 'dataset') {
      global $dataset;
      $dataset = $node;
    }
  }
 
  if ($node->type == 'dataset' && $op == 'view') {
	tow_dataset_extract_statistics($node);
    tow_dataset_summary($node);
    tow_dataset_update_statistics($node);
  }
  
  // Redirect from node/[table-nid] pages to table/[table-nid]
  if ($node->type == 'table' && $op == 'view') {
    $args = arg();
    if (count($args) == 2 && $args[0] == 'node')
      drupal_goto('table/' . $node->nid, NULL, NULL, 301);
  }
  
  // Redirect from node/[record-nid] to node/[record-nid]/edit
  if  ($node->type == 'record' && $op == 'view')
    drupal_goto('node/' . $node->nid . '/edit', NULL, NULL, 301);
    
}

/**
 * Implementation of hook_block().
 */
function tow_block($op = 'list', $delta = 0) {
  if ($op == 'list') {
    $blocks['create_table']['info'] = t('Create table');
    $blocks['pma_menu']['info'] = t('PhpMyAdmin menu');
    $blocks['dataset_badge']['info'] = t('Dataset badge');
    $blocks['dataset_stats']['info'] = t('Dataset statistics');
    return $blocks;
  }
  elseif($op == 'view') {
    if (user_access('access content')) {
      if($delta == 'create_table') { 
	    return tow_dataset_create_table_block();
      }
      if ($delta == 'pma_menu') {
	    return tow_pma_menu_block();
      }
      if ($delta == 'dataset_badge') {
	    return tow_dataset_badge_block();
      }
      if ($delta == 'dataset_stats') {
	    return tow_dataset_stats_block();
      }
    }
  }
  
}

/**
 * Implementation of hook_form_alter().
 */
function tow_form_alter(&$form, &$form_state, $form_id) {  
    
  if ($form_id == 'dataset_node_form' || $form_id == 'table_node_form') {
    $form['#submit'][] = 'tow_submit_maintanance_mode';
  }
  
  if ($form_id == 'table_node_form') {
    tow_table_form_alter(&$form, &$form_state);
  }
  
  if ($form_id == 'record_node_form') {
    tow_record_form_alter(&$form, &$form_state);
  }
  
  if ($form_id == 'node_delete_confirm' || $form_id == 'tow_table_truncate_confirm') {
    $node = node_load($form['nid']['#value']);
    switch ($node->type) {
      case 'dataset':
        global $dataset;
        $dataset = (object)(array('nid' => $node->nid, 'title' => $node->title));
        break;
      case 'table':
        global $dataset;
        global $table;
        $dataset = node_load($node->field_dataset['0']['nid']);
        $dataset = (object)array('nid' => $dataset->nid, 'title' => $dataset->title);
        $table = (object)array('nid' => $node->nid, 'title' => $node->title);
        break;
      case 'record':
        global $dataset;
        global $table;
        $table = node_load($node->field_table['0']['nid']);
        $dataset = node_load($table->field_dataset['0']['nid']);
        $dataset = (object)array('nid' => $dataset->nid, 'title' => $dataset->title);
        $table = (object)array('nid' => $table->nid, 'title' => $table->title);
        break;
    }
  
  }
  
  // add cancel button to record, table and dataset node editing forms.
  if ($form_id == 'record_node_form' || $form_id == 'table_node_form' || $form_id == 'dataset_node_form')
  $form['buttons']['cancel'] = array(
    '#type' => 'submit',
    '#value' => t('Cancel'),
    '#weight' => 20
  );
  
}

/**
 * Submit callback for table and dataset editing form
 * Checks whether status of node is changed. If it is changed call tow_maintanance_mode function
 */
function tow_submit_maintanance_mode($form, &$form_state) {
  if ($form['options']['status']['#default_value'] != $form_state['values']['status'])
    tow_maintanance_mode($form_state['values']['status'], $form_state['values']['nid'], $form_state['values']['type']);
}

/**
 * When table is published/unpublished, perform the same change of status for records connected
 * When dataset is published/unpublished, perform the same change of status for tables connected and recursively call this function for each table
 */
function tow_maintanance_mode($status, $nid, $type) {
  
  if ($status == 1)
    $function = 'node_publish_action'; //TODO: do we really need to call them? (do we need watchdog be affected?)
  elseif ($status == 0)
    $function = 'node_unpublish_action';
  
  $children_type = _tow_children_type($type);
  $res = db_query("SELECT nid FROM {content_type_%s} WHERE field_{%s}_nid = %d", $children_type, $type, $nid);
  
  if ($type == 'dataset')
    while($node = db_fetch_object($res)) {
      $node = node_load($node->nid);
      $function($node);
      node_save($node);
      tow_maintanance_mode($status, $node->nid, 'table');
    }
  elseif ($type == 'table')
    while($node = db_fetch_object($res)) {
      $node = node_load($node->nid);
      $function($node);
      node_save($node);
    }
}

/**
 * @return "record" for "table" and "table" for "dataset"
 * @param unknown_type $type
 */
function _tow_children_type($type) {
  switch ($type) {
    case 'table':
      $children_type = 'record';
      break;
    case 'dataset':
      $children_type = 'table';
      break;
  }
  return $children_type;
}  

/**
 * For @param $value return boolean string
 */
function _tow_format_bool($value) {
  if ($value)
    return 'true';
  if ($value === '0')
    return 'false';
}

/**
 * For @param $value return 1 if it is "true" or 1. Not case-sensitive 
 */
function _tow_bool_to_int($value) {
  if (strtolower($value) == 'true')
    return 1;
  if ($value == 1)
    return 1;
  return 0;
}