<? 

/**
 * Implementation of hook_search().
 */
function tow_inner_search_search($op = 'search', $keys = NULL) {

  switch ($op) {
	case 'name':
	  return t('Search');

	case 'reset':
	  apachesolr_clear_last_index('apachesolr_search');
	  return;

	case 'status':
	  return apachesolr_index_status('apachesolr_search');

	case 'search':
	  $filters = isset($_GET['filters']) ? $_GET['filters'] : '';
	  $solrsort = isset($_GET['solrsort']) ? $_GET['solrsort'] : '';
	  $page = isset($_GET['page']) ? $_GET['page'] : 0;
	  try {
		$results = apachesolr_search_execute($keys, 
		$filters, 
		$solrsort, 
		'search_dataset', $page);
		return $results;
	  }
	  catch (Exception $e) {
		watchdog('Apache Solr', nl2br(check_plain($e->getMessage())), NULL, WATCHDOG_ERROR);
		apachesolr_failure(t('Solr search'), $keys);
	  }
	  break;
  } // switch
} 

function tow_inner_search_search_page($results) {
	// Display parameters for datatable theme
	$parameters_full['datatable_options'] = array(
	'bLengthChange' => FALSE,
	'bPaginate' 	=> FALSE,      
	'bFilter'		=> FALSE,  
	'bSort' 		=> TRUE,
	'bInfo'	    	=> FALSE,
	'sScrollX'		=> '100%',
	'sScrollY'		=> '300',
	'bScrollCollapse' => true,
	);
	return theme('datatable', $results['headers'], $results['rows'], $parameters_full);
}

/**
 * Implementation of hook_theme().
 */
// function tow_inner_search_theme () {
  // return array(
    // 'tow_inner_search_search_result' => array(
      // 'arguments' => array('result' => NULL, 'type' => NULL),
//     'file' => 'search.pages.inc',
      // 'template' => 'search-result-tow-inner-search',
    // ),
    // 'tow_inner_search_search_results' => array(
      // 'arguments' => array('results' => NULL, 'type' => NULL),
      // 'file' => 'search.pages.inc',
      // 'template' => 'search-results',
    // ),
//  );
//}