<? 

/**
 * Implementation of hook_search().
 */
function tow_inner_search_search($op = 'search', $keys = NULL) {

  switch ($op) {
	case 'name':
	  return t('Search');

	case 'reset':
	  apachesolr_clear_last_index('apachesolr_search');
	  return;

	case 'status':
	  return apachesolr_index_status('apachesolr_search');

	case 'search':
	  $filters = isset($_GET['filters']) ? $_GET['filters'] : '';
	  $solrsort = isset($_GET['solrsort']) ? $_GET['solrsort'] : '';
	  $page = isset($_GET['page']) ? $_GET['page'] : 0;
	  try {
		$results = apachesolr_search_execute($keys, 
		$filters, 
		$solrsort, 
		'search_dataset/' . tow_search_inner_get_nid(), $page, 'tow_inner_search');
		return $results;
	  }
	  catch (Exception $e) {
		watchdog('Apache Solr', nl2br(check_plain($e->getMessage())), NULL, WATCHDOG_ERROR);
		apachesolr_failure(t('Solr search'), $keys);
	  }
	  break;
  } // switch
} 

/**
 * Implementation of hook_search_page().
 */
 function tow_inner_search_search_page($results) {
	// Display parameters for datatable theme
	$parameters_full['datatable_options'] = array(
	'bLengthChange' => FALSE,
	'bPaginate' 	=> FALSE,      
	'bFilter'		=> FALSE,  
	'bSort' 		=> TRUE,
	'bInfo'	    	=> FALSE,
	'sScrollX'		=> '100%',
	'sScrollY'		=> '100%',
	'bScrollCollapse' => true,
	);
	return theme('datatable', $results['headers'], $results['rows'], $parameters_full);
}

function tow_inner_search_finalize_query(&$query, &$params) {
	$tag = '';
	foreach($params['fq'] as &$filter) {
		if (preg_match('/(?<=^\()\w{1,}(?=:)/', $filter, $matches)) {
			$tag = $matches[0];
		} elseif (preg_match('/(?<=^)\w{1,}(?=:)/', $filter, $matches)) {
			$tag = $matches[0];
		}
		if ($tag) 
			$filter = '{!tag=' . $tag . '}' . $filter;
	}
}