; This file was auto-generated by drush make
core = 6.x

api = 2
projects[drupal][version] = "6.x"

; Modules
projects[admin_menu][version] = "1.6"

projects[ahah_helper][version] = "2.x-dev"

projects[apachesolr][version] = "1.5"

projects[backup_migrate][version] = "2.4"

projects[ctools][version] = "1.8"

projects[coder][version] = "2.0-rc1"

projects[cck][version] = "2.9"

projects[datatables][version] = "1.0"

projects[date][version] = "2.7"

projects[devel][version] = "1.23"

projects[heartbeat][version] = "4.11"

projects[gigya][version] = "3.0"

projects[jquery_update][version] = "2.0-alpha1"

projects[menu_block][version] = "2.4"

projects[rdf][version] = "1.0-alpha8"

projects[rules][version] = "1.4"

projects[simpletest][version] = "2.11"

projects[token][version] = "1.15"

projects[views][version] = "2.12"

projects[views_customfield][version] = "1.0"

projects[votingapi][version] = "2.3"

projects[vote_up_down][version] = "3.1"

projects[yui][version] = "1.3"

projects[yui_calendar][version] = "1.0"

; Themes
projects[fusion][subdir] = "themes"
projects[fusion][version] = "1.12"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tow][download][type] = ""
projects[tow][download][url] = ""
projects[tow][type] = "module"


